slam_toolbox:
  ros__parameters:
    scan_topic: /scan
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    tf_broadcast: true
    transform_publish_period: 0.05
    publish_tf_map: true
    publish_tf: true
    use_sim_time: true
    max_laser_range: 3.5
    map_update_interval: 0.2